name: Doug Sturgess Photography
favicon: null
layout_spectrum: 0.824897926999256
typography_spectrum: 0.371389236766845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5237539699301124
  lightness: 0.45347097935155034
  saturation: 0.23328130063600838
  rhythmicContrast: 0.7854940979741514
purpose: []
