name: Doug Sturgess Photography
favicon: null
layout_spectrum: 0.01366
typography_spectrum: 0.6104
title: DOUG STURGESS PHOTOGRAPHY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#f4dc00'
    - '#9e311e'
    - '#897700'
    - '#3f6ea6'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
